### ISSUE TITLE
npm install fails on node 5.3

### ISSUE THREAD

**Issue by iamgoodbytes** [solidshops/devshop#6]
npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/Cellar/node/5.3.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! deasync@0.1.4 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the deasync@0.1.4 install script 'node ./build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the deasync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls deasync
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jorre/GoodBytes/htdocs/shop.schapenkop.be/devshop/npm-debug.log
~/G/h/s/devshop ❯❯❯ node -v                                                                        ⏎
v5.3.0

**Comment by driesdroesbeke** [comment]
Should be resolved. I added node 5.3 to travis.
